# vTiger installation
joomla_db_user: joomla
joomla_db_password: joomla
joomla_db_name: joomla
joomla_root_path: /var/lib/joomla/webapp/

# vTiger default configuration
sso_enabled: "false"
connec_enabled: "false"
maestrano_environment: "production"
server_hostname: "server_hostname"
api_key: "api_key"
api_secret: "api_secret"